language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build
  on:
    branch: master
'':
  travis:
    yml:
      secure: YDXWKv9/BKG9w9Va6kRBeIMDt4ZsVQOGRYR00oZmymJkkCHmL0ZRlReXSaEF2jGy8wlMDMGO9j/2fqylXSd14Seo8oDz1cdBiYSp51mj6AGswjskpf582v8wSRD3HJeIQ6fGlRVPmeuF8Dt0wj17+ysXj+uBxGu/s+02cVqlcBQZoQCvpaRTupsgurs2zPQOBrv2Tfq1F94SPYrn5XvIBDT21shXYi8i126yWebUp61CXrZyCfILCHZXzvIAUIuFpPjDFozOJOu+zL79fCQXylUXgp+AWdgZ21kwVQl5pD6oJOrQp0l6G+M5jA7hDsShgoUsZWU+3SNvUasc2dd88U0o/54EztUz9wR8v7EVqJMda8iLWmWAoOphYt/mz4C70UaYOTbqwXWTnMR+KWd8cczQxsVVETSM5AXmWZiMp55bR3lw7Fi8cWruQN1b7ZzLsT5X2hAp3FMH0P4mSV2NxcBSWi23AhYJ3O8H+ZIjqLAXQl6N8Gl49qr1QnugNDk4eNB+MY4GzgOwRyYd8zdZgjd2GsArASWxFl6nI3cC83lzVAcTovs/gqEQOmv1ARqaMklHfcMVtdaSzjraAYEnyNCl3gT7sZSSx2JL/xCR/MFE+TLMx/Sv2ch+PrDLMxV+k9UD+GKQYaEDVW5Qpu3mlBLixk1H5i9Dcjm3bRNRikA=
